Remove icons in standalone search
tech-matters/flex-plugins pull request #251
Opened 2020-11-27 20:38 UTC by andvirga

2020-11-27 21:05 UTC, nickhurlburt requested changes
Mostly looking good, but some major issues.  Biggest thing is that whenever I do an in-contact search, then click into the cases search tab, Flex gets an error and forces a hard refresh.  Several errors and warnings get reported when this happens.  Please test out in-contact search to see this.

2020-11-30 12:52 UTC, andvirga commented on plugin-hrm-form/src/components/ContactDetails.tsx
>  import { DetailsContainer, NameContainer, DetNameText, ContactDetailsIcon } from '../styles/search';
Good catch! Done!

2020-11-30 15:45 UTC, andvirga commented on plugin-hrm-form/src/components/search/ContactPreview/ConnectContact.tsx
> +        {showConnectIcon && <ConnectIcon />}
Solved!

2020-11-30 20:24 UTC, andvirga commented
@nickhurlburt the flex reboot issue is solved now. (I've removed the `<form>` wrapper and replaced it with a `<div role='form'>` like @GPaoloni instructed.

2020-12-01 00:44 UTC, nickhurlburt approved these changes
Looks good to me!

2020-12-01 12:53 UTC, murilovmachado approved these changes
Looks good!

2020-12-01 13:16 UTC, merged