[WIP] View case on standalone search
tech-matters/flex-plugins pull request #252
Opened 2020-11-30 23:25 UTC by murilovmachado

Jira: https://bugs.benetech.org/browse/CHI-345

This PR implements clinking on **View Case** on Standalone Search.

WIP:
- Return to Search Results button
- Change BottomBar buttons to display **Close** button, instead of **Update Case** and **Cancel**
- Tests

<img width="1435" alt="Screen Shot 2020-11-30 at 20 21 27" src="https://user-images.githubusercontent.com/1504544/100677604-1f42cc80-334a-11eb-9e05-6223594fbb3d.png">

2020-12-01 00:35 UTC, nickhurlburt reviewed
Looking at the functionality, looks good.  The one thing to add to your list of ToDos is to prevent people from editing the case summary.  If we don't let them save it, we shouldn't allow editing.

I can't look at in-contact case search because this branch still has the reloading issue, but I assume it will look the same as standalone.

Nice to see Case move to TS!

2020-12-01 13:45 UTC, GPaoloni reviewed
Looks good so far!! Just one thing, I'm receiving the following error when trying to "View" the contact from the case page. I've been working with that `isContactlessTask` recently, so maybe I can help you with this issue if needed. 
![Screenshot from 2020-12-01 10-32-31](https://user-images.githubusercontent.com/15805319/100747615-0de8d700-33c1-11eb-9913-f246188b76d5.png)

2020-12-01 13:45 UTC, GPaoloni commented on plugin-hrm-form/src/states/ContactState.js
> +export const standaloneTaskSid = 'standalone-task-sid';
Neat trick, using this constant as key to reuse search/routing! One question tho, why does this live in `ContactState`? Is there something related to the contact form here (afaik that's what this reducer is about)?

2020-12-01 13:46 UTC, GPaoloni commented on plugin-hrm-form/src/states/ContactState.js
> +export const standaloneTaskSid = 'standalone-task-sid';
Also, giving it the name of standalone task may be confusing, as that's how I've been calling the "offline contact" (because is not really offline) but this is not related to that feature. Not saying you have to change it, just wondering if a there is a better name for this.

2020-12-01 14:00 UTC, murilovmachado commented on plugin-hrm-form/src/states/ContactState.js
> +export const standaloneTaskSid = 'standalone-task-sid';
To be honest, I just don't know the best place to keep this const =)
I'll try to find a better place for it (I've been moving it around)

2020-12-01 14:07 UTC, andvirga commented on plugin-hrm-form/src/components/search/index.tsx
> +        return <Case task={props.task as any} handleCompleteTask={() => null} />;
Is there a type that we can use here instead of `any`?

2020-12-01 14:09 UTC, murilovmachado commented on plugin-hrm-form/src/components/search/index.tsx
> +        return <Case task={props.task as any} handleCompleteTask={() => null} />;
oops, I don't need to case it to **any** anymore, I've forgot to remove it. Thanks for catching it.

2020-12-01 14:37 UTC, GPaoloni commented on plugin-hrm-form/src/states/ContactState.js
> +export const standaloneTaskSid = 'standalone-task-sid';
Maybe the root `states/index.ts` file? As this is something shared between a few reducers. Just an idea tho, the one that makes more sense to you will be ok!

2020-12-01 23:38 UTC, murilovmachado commented
@nickhurlburt If you have time, please take another look. All functionalities are in place, I'm just working on the tests now. I plan on merging this tomorrow morning.

2020-12-02 00:57 UTC, nickhurlburt requested changes
When I go to case view in standalone search and then click to view a note, I get an all-white screen and this error in the console:
```
plugin-hrm-form.js:335757 Uncaught TypeError: Cannot read property 'isContactlessTask' of undefined
    at getConversationDuration (plugin-hrm-form.js:335757)
    at adaptFormToContactDetails (plugin-hrm-form.js:319814)
    at ViewContact (plugin-hrm-form.js:320797)
    at renderWithHooks (react-dom.development.js:14938)
    at mountIndeterminateComponent (react-dom.development.js:17617)
    at beginWork (react-dom.development.js:18731)
    at HTMLUnknownElement.callCallback (react-dom.development.js:182)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:231)
    at invokeGuardedCallback (react-dom.development.js:286)
    at beginWork$1 (react-dom.development.js:23338)
    at performUnitOfWork (react-dom.development.js:22289)
    at workLoopSync (react-dom.development.js:22265)
    at performSyncWorkOnRoot (react-dom.development.js:21891)
    at react-dom.development.js:11224
    at unstable_runWithPriority (react.development.js:2685)
    at runWithPriority$1 (react-dom.development.js:11174)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11219)
    at flushSyncCallbackQueue (react-dom.development.js:11207)
    at discreteUpdates$1 (react-dom.development.js:22028)
    at discreteUpdates (react-dom.development.js:803)
    at dispatchDiscreteEvent (react-dom.development.js:4291)
getConversationDuration @ plugin-hrm-form.js:335757
adaptFormToContactDetails @ plugin-hrm-form.js:319814
ViewContact @ plugin-hrm-form.js:320797
renderWithHooks @ react-dom.development.js:14938
mountIndeterminateComponent @ react-dom.development.js:17617
beginWork @ react-dom.development.js:18731
callCallback @ react-dom.development.js:182
invokeGuardedCallbackDev @ react-dom.development.js:231
invokeGuardedCallback @ react-dom.development.js:286
beginWork$1 @ react-dom.development.js:23338
performUnitOfWork @ react-dom.development.js:22289
workLoopSync @ react-dom.development.js:22265
performSyncWorkOnRoot @ react-dom.development.js:21891
(anonymous) @ react-dom.development.js:11224
unstable_runWithPriority @ react.development.js:2685
runWithPriority$1 @ react-dom.development.js:11174
flushSyncCallbackQueueImpl @ react-dom.development.js:11219
flushSyncCallbackQueue @ react-dom.development.js:11207
discreteUpdates$1 @ react-dom.development.js:22028
discreteUpdates @ react-dom.development.js:803
dispatchDiscreteEvent @ react-dom.development.js:4291

plugin-hrm-form.js:295211 The above error occurred in the <ViewContact> component:
    in ViewContact (created by Connect(ViewContact))
    in Connect(ViewContact) (at Case.tsx:153)
    in Case (created by Connect(Case))
    in Connect(Case) (created by Context.Consumer)
    in WithTaskContext(Connect(Case)) (at search/index.tsx:161)
    in Search (created by Connect(Search))
    in Connect(Search) (created by Context.Consumer)
    in WithTaskContext(Connect(Search)) (at StandaloneSearch.tsx:15)
    in div (created by StandaloneSearchContainer)
    in StandaloneSearchContainer (at StandaloneSearch.tsx:14)
    in StandaloneSearch (at setUpComponents.js:378)
```
There are also a few other errors in the console, but I'm not sure if they're related to this PR.

I'm clicking on case #660, then 'View' for the contact:
![image](https://user-images.githubusercontent.com/10714292/100813908-4dc9b180-33f5-11eb-910a-54b4dea23129.png)

It consistently errors when I do that.  It also errors when I click 'View' on the contact in the timeline when adding a new case.  It does *not* error when I click 'View' on a note in the timeline.

Otherwise, case summary is not editable as intended!

2020-12-02 01:01 UTC, murilovmachado commented
@nickhurlburt you're right, Gian noticed this error, too. I've completely forgotten to fix it. I'll do that tomorrow.

2020-12-02 22:42 UTC, andvirga approved these changes
Looks good!

2020-12-03 00:26 UTC, murilovmachado commented
@nickhurlburt Now I believe I've fixed those issues. Can you take another look at the functionality? Also, this task was trickier than I had expected, so please check 3 scenarios:
- View Case from Standalone Search
- View Case from normal Search
- View Case when creating a case

Tomorrow I'll fix the tests, didn't have time to fix them yet.

2020-12-03 00:28 UTC, nickhurlburt commented
Taking a look

2020-12-03 00:40 UTC, nickhurlburt approved these changes
@murilovmachado I ran through those three cases and poked around a little more, and this looks good to me.  Please try to have this out on staging for Joan in the morning so she can get started.  If necessary, I'd be fine with commenting out tests in order to merge and deploy.  (And then following up right after with a PR to fix tests, of course.)  Thanks for making this work!

2020-12-03 14:37 UTC, GPaoloni approved these changes
Looks great!

2020-12-03 14:37 UTC, GPaoloni commented on plugin-hrm-form/src/components/StandaloneSearch.tsx
> +import { standaloneTaskSid } from '../states/ContactState';
Sorry to bother you, but I insist in moving this out from here, as I'm now working on what will be the replacement of `ContactState`, and also don't think this is really related to this reducer.

2020-12-03 14:37 UTC, GPaoloni commented on plugin-hrm-form/src/states/routing/types.ts
> +      subroute?: typeof NewCaseSubroutes[keyof typeof NewCaseSubroutes];
Is this intentional? `NewCaseSubroutes` as `tabbed-forms` subroutes?

2020-12-03 14:37 UTC, GPaoloni commented on plugin-hrm-form/src/states/case/types.ts
> +  contact?: any; // TODO: create Contact type
Maybe this is the type you expect here? (it's a bit outdated, but most of the stuff is in place).

https://github.com/tech-matters/flex-plugins/blob/3896f9d9115b4942d9d5d46af24da4c6c367022d/plugin-hrm-form/src/types/types.ts#L73

2020-12-03 15:16 UTC, murilovmachado commented on plugin-hrm-form/src/states/routing/types.ts
> +      subroute?: typeof NewCaseSubroutes[keyof typeof NewCaseSubroutes];
yes, all routes now have Case.

2020-12-03 15:17 UTC, murilovmachado commented on plugin-hrm-form/src/states/case/types.ts
> +  contact?: any; // TODO: create Contact type
This is just one part pf the type, the `rawJson`. It's missing more stuff. We can add them later.

2020-12-03 17:51 UTC, merged