Forms Generators
tech-matters/flex-plugins pull request #256
Opened 2020-12-02 15:40 UTC by GPaoloni

Jira: https://bugs.benetech.org/browse/CHI-317

This PR:
- improve styles for the forms, making them look more like what we have now.
- reorganizes styles and some UI generation helpers

WIP: 
- CI
- tests for each input type

2020-12-02 19:39 UTC, nickhurlburt approved these changes
I haven't looked in great detail, but I think I understand the high level, and looks good to me!

2020-12-02 19:39 UTC, nickhurlburt commented on plugin-hrm-form/src/components/common/forms/formGenerators.tsx
> + * Creates a Form with each input conntected to RHF's wrapping Context, based on the definition.
s/conntected/connected

2020-12-02 19:39 UTC, nickhurlburt commented on plugin-hrm-form/src/components/common/forms/formGenerators.tsx
> +export const buildTwoColumnFormLayout = (formItems: JSX.Element[]) => {
Without having looked through all the code, this looks like it's automatically splitting the first and second halves of the `formDefinition` into the two columns.  There may be times when we need a manual split, for example, if we have several small inputs and then a big `textarea`.  If that's still possible with the code as-is, then no problem.

2020-12-14 19:04 UTC, andvirga commented on plugin-hrm-form/src/HrmFormPlugin.js
> +    loadCSS('https://use.fontawesome.com/releases/v5.15.1/css/solid.css');
Can we move this to an environment variable? To easily update or change the CDN if needed.

2020-12-14 19:53 UTC, andvirga commented on plugin-hrm-form/src/components/common/forms/formGenerators.tsx
>   * @param {FormItemDefinition} def Definition for a single input of a Form
The area that I wanted to comment is out of the PR (lines 415 - 432)
``` javascript
switch (def.type) {
    case 'input':
    case 'numeric-input':
    case 'textarea':
    case 'date-input':
    case 'time-input':
      return '';
    case 'select':
      return def.options[0].value;
    case 'dependent-select':
      return def.defaultOption.value;
    case 'checkbox':
      return false;
    case 'mixed-checkbox':
      return def.initialChecked === undefined ? 'mixed' : def.initialChecked;
    default:
      return null;
  }
```

Can we create an object that holds all the different types of Inputs? It should look like this:

```javascript
const InputTypes = Object.freeze({
  INPUT: 'input',
  NUMERIC_INPUT: 'numeric-input',
  TEXTAREA: 'textarea',
  DATE_INPUT: 'date-input',
  TIME_INPUT: 'time-input',
  SELECT: 'select',
})
```

2020-12-14 20:47 UTC, GPaoloni commented on plugin-hrm-form/src/HrmFormPlugin.js
> +    loadCSS('https://use.fontawesome.com/releases/v5.15.1/css/solid.css');
Makes sense. Where do think we should place it? W don't have a .env in this repo, but maybe Twilio account setting?

2020-12-14 21:01 UTC, GPaoloni commented on plugin-hrm-form/src/components/common/forms/formGenerators.tsx
>   * @param {FormItemDefinition} def Definition for a single input of a Form
Actually that information is already in the type. We can do that if you consider it to be useful of course, but I don't see the extra benefit over TS.
![Screenshot from 2020-12-14 17-55-12](https://user-images.githubusercontent.com/15805319/102134812-cb4de280-3e35-11eb-93d6-ac7fb4925031.png)

2020-12-14 21:23 UTC, andvirga requested changes
This PR looks great! I've tested your branch and everything seems to work fine! 
I've only left two small comments, it would be good if you can address them.

2020-12-14 21:27 UTC, andvirga commented on plugin-hrm-form/src/HrmFormPlugin.js
> +    loadCSS('https://use.fontawesome.com/releases/v5.15.1/css/solid.css');
I would say to choose the easiest / simpler solution. I'm not very familiarized with the Twilio account setting but if that option is simple let's go with that.

2020-12-14 21:34 UTC, andvirga commented on plugin-hrm-form/src/components/common/forms/formGenerators.tsx
>   * @param {FormItemDefinition} def Definition for a single input of a Form
I believe that having this object will be very useful, for example, if you want to define a new input field in the JSON you can do something like this, and you can easily know which are the available types for the field you want to create.
Of course, let's do this only if this change doesn't add too much complexity.

```javascript  
{
    name: 'test',
    type: InputTypes.DATE,
    label: 'Test',
    required: { value: true, message: 'RequiredFieldError' },
  },
```

2020-12-15 14:39 UTC, murilovmachado approved these changes
Looks good!

2020-12-15 14:39 UTC, murilovmachado commented on plugin-hrm-form/src/components/common/forms/formGenerators.tsx
> +                  {rules.required && <RequiredAsterisk />}
I'm curious how these inputs work fine when I look at this line:
`{rules.required && <RequiredAsterisk />}`.

Currently, `RequiredAsterisk` needs a `field` param:
```
const RequiredAsterisk = ({ field }) => {
  const isRequired = field.validation && field.validation.includes(ValidationType.REQUIRED);
  return isRequired && <span style={{ color: 'red' }}>*</span>;
};
```
Calling `<RequiredAsterisk />` (without `field` param) should give an error like: 
`Tried calling validation of undefined`.

But it looks like the contactless tab is using them without throwing an error.

2020-12-15 14:39 UTC, murilovmachado commented on plugin-hrm-form/src/components/common/forms/formGenerators.tsx
> +                  {rules.required && <RequiredAsterisk />}
**Update:** Oh, this is not using our old `RequiredAsterisk`, but a custom one defined in this same file. I got it.

2020-12-15 17:50 UTC, andvirga commented on plugin-hrm-form/src/components/common/forms/formGenerators.tsx
>   * @param {FormItemDefinition} def Definition for a single input of a Form
**Update:** as we discussed, TS already helps you to identify input types, we don't need an additional frozen object.

2020-12-17 20:32 UTC, GPaoloni commented on plugin-hrm-form/src/HrmFormPlugin.js
> +    loadCSS('https://use.fontawesome.com/releases/v5.15.1/css/solid.css');
What do you think @murilovmachado ? Should we put this in config or leave it hardcoded? I've been thinking and I don't see this changing very often.

2020-12-17 20:42 UTC, nickhurlburt commented on plugin-hrm-form/src/HrmFormPlugin.js
> +    loadCSS('https://use.fontawesome.com/releases/v5.15.1/css/solid.css');
This is really up to you all, but if you decide to keep it hard coded I don't see that as a problem.

2020-12-28 18:45 UTC, merged