Case view bug fixes
tech-matters/flex-plugins pull request #263
Opened 2020-12-07 16:17 UTC by GPaoloni

This PR is related to https://github.com/tech-matters/hrm/pull/64

Fixed the following bugs for contactless/offline tasks: 
1. The icon isn’t right in the timeline for standalone-entered tasks
2. The contact summary doesn’t appear in timeline
3. When clicking on View it says “Not yet implemented”

2020-12-07 21:33 UTC, nickhurlburt requested changes
I added a chat offline contact and created a new case from it and that worked fine, but when I searched for it I got this:
![image](https://user-images.githubusercontent.com/10714292/101408008-94555b00-3890-11eb-843e-0f78e596c8f2.png)

(I had also added a note.)  This is just using the HRM on staging and not the HRM with the recent changes, so that may be the reason why it's failing.

2020-12-07 21:33 UTC, nickhurlburt commented on plugin-hrm-form/src/components/case/TimelineIcon.jsx
> +    default:
Having a different default is a good idea here

2020-12-07 21:33 UTC, nickhurlburt commented on plugin-hrm-form/src/components/case/Timeline.jsx
> +              <TimelineIcon icon={activity.icon} />
I see, here we do use the `icon` from the backend.  But why not reuse the same idea further up in this file, `const icon = task.channelType === 'default' ? form.contactlessTask.channel : task.channelType;` but `activity.type` instead of `task.channelType`?  It makes so much more sense to me to decide what icon to use in the frontend.

2020-12-08 14:53 UTC, andvirga commented on plugin-hrm-form/src/components/case/Timeline.jsx
> +        const icon = task.channelType === 'default' ? form.contactlessTask.channel : task.channelType;
Are we 100% sure that when `task.channelType = 'default'` --> `form.contactlessTask` has a value and it's not `undefined`?

2020-12-08 14:57 UTC, andvirga approved these changes
Looks good! I've only one concern that I've left in a comment.

2020-12-08 15:20 UTC, GPaoloni commented on plugin-hrm-form/src/components/case/Timeline.jsx
> +        const icon = task.channelType === 'default' ? form.contactlessTask.channel : task.channelType;
Yes, it's required in order to submit the form!

2020-12-08 15:39 UTC, andvirga approved these changes
Approved!

2020-12-08 15:51 UTC, nickhurlburt approved these changes
Looks good to me

2020-12-08 15:53 UTC, murilovmachado approved these changes

2020-12-08 16:24 UTC, merged

2020-12-08 16:35 UTC, GPaoloni commented
Deployed to staging.