[WIP] Addressed frontend changes
tech-matters/flex-plugins pull request #371
Opened 2021-03-02 21:33 UTC by GPaoloni

This PR is a continuation of https://github.com/tech-matters/flex-plugins/pull/361.

You can point to dev env for serverless in order to test this.

This PR:
- Adds `addOfflineContact` boolean property to routing reducer to tell the app that the user is in the process of completing a contacttless task form (even if switch between tasks, state is preserved). The offline contact forms are shown if a) there is no selected Twilio task, and b) `addOfflineContact` is set to `true`.
- "Add Offline Task" button now dispatches a `recreateTaskState` action, to reuse all of our existing reducers logic. "Cancel Offline Task" simply dispatches a `removeTaskState`
- Rework on our TaskView components tree. Now only one single place is using Twilio's `withTaskContext` helper, and from there and based on above routing information, renders the proper forms. A fake Task (`CustomITask`) is passed down the component tree if the user is filling an offline task.
- `assignOfflineContact` serverless function is used to create-assing-complete a new Twilio task in behalf of someone else, but now we use the taskSid of such a task as the unique identifier for the form being submited by the user. Still have some gotchas on this, as if a step fails here, we can end up with inconsistent states between Insights and HRM.
- The form being submitted to HRM is still stored as if the issuer was the creator. We need to decide which approach to take in order to resolve the search issues mentioned in previous PR.
> The twilioWorkerId column of contact stored in the backend is the one of the issuer, not the target counselor. This causes the contact to appear in behalf of the issuer and not the target counselor. For this to be fixed we can either use the target counselor's sid in twilioWorkerId (but then the information that this task was submitted by issuer is lost, unless saved inside the raw json or a new column) or change the search query when contacts are offline contacts (this may slow down the query and increase it's complexity). Same happens for cases.

2021-03-04 19:27 UTC, andvirga commented on plugin-hrm-form/src/components/ContactDetails.tsx
>    detailsExpanded: any;
Can we define these types? If it's too complex ignore my comment.

2021-03-04 19:31 UTC, andvirga commented on plugin-hrm-form/src/components/CustomCRMContainer.tsx
> +  const { addOfflineContact } = state[namespace][routingBase];
Please rename this to: `isAddingOfflineContact` 😉

2021-03-04 19:35 UTC, andvirga commented on plugin-hrm-form/src/components/OfflineContactButton/index.tsx
> +    addOfflineContact,
Also, you can rename it here 🙏🏻

2021-03-04 19:48 UTC, andvirga commented on plugin-hrm-form/src/components/TaskView.tsx
> +  const shouldRecreateState = !contactFormStateExists || !routingStateExists || !searchStateExists;
Just double-checking the logic: the state should be recreated if **any** of these conditions apply:
- contact form state doesn't exist
- routing state doesn't exist
- search state doesn't exist

Do I understand this right?

2021-03-04 19:53 UTC, andvirga commented on plugin-hrm-form/src/components/callTypeButtons/CallTypeButtons.jsx
> +    if (isOfflineContactTask(task)) {
I really appreciate these improvements

2021-03-04 20:02 UTC, andvirga commented on plugin-hrm-form/src/services/ContactService.ts
> +export async function saveToHrm(task, form, workerSid, helpline, uniqueIdentifier, shouldFillEndMillis = true) {
Is this `uniqueIdentifier` the twilioWorkerId of the target counselor?

2021-03-04 20:06 UTC, andvirga commented on plugin-hrm-form/src/services/formSumbissionHelpers.ts
> +    const contact = await saveToHrm(task, contactForm, workerSid, helpline, inBehalfTask.sid);
It seems that I've found the answer for this my previous question 🤣 
In this case, I would suggest to rename `uniqueIdentifier` In `saveToHrm` function to a more descriptive name (i.e: `InBehalfTwilioWorkerId` or `TargetCounselorTwilioWorkerId`)

2021-03-04 20:07 UTC, andvirga commented on plugin-hrm-form/src/services/formSumbissionHelpers.ts
> +  console.log('>>>>>>', inBehalfTask, contact);
Remove this `console.log` line

2021-03-04 20:14 UTC, andvirga commented on plugin-hrm-form/src/types/types.ts
> +}
Bravo!

2021-03-04 20:19 UTC, andvirga requested changes
I believe that I mostly get the idea of your changes, however, I'm not quite sure which is the best approach for storing the right Counselor in the DB. 
In my humble opinion, I would prefer to store the TargetCounselor as an extra parameter in the DB, instead of changing the search queries (that could lead to confusions),

2021-03-05 13:45 UTC, andvirga approved these changes
Tested it in my local environment and it's working great:
I've created an offline task with you as Conselor, this is the result:

```json
   "contactlessTask":{
      "date":"2021-03-05",
      "time":"10:35",
      "channel":"whatsapp",
      "createdOnBehalfOf":"WKef74b75b8b09f4aac2482f3ee419a302"
   },
```

2021-03-09 02:28 UTC, nickhurlburt commented
This is showing the "No active tasks" Panel.  Is that intentional, or an oversight?

![image](https://user-images.githubusercontent.com/10714292/110409369-037f4e80-803c-11eb-80ab-10317bc3de9e.png)

2021-03-09 02:31 UTC, nickhurlburt commented
Minor thing:  notice where I circle here that the corners are offset.  This may not be a problem if we remove the "No Tasks" component.

<img width="133" alt="Screen Shot 2021-03-08 at 6 28 42 PM" src="https://user-images.githubusercontent.com/10714292/110409566-5822c980-803c-11eb-868f-458492c486a8.png">

2021-03-09 02:35 UTC, nickhurlburt commented
Can we alphabetize the options in the counsellor dropdown?  I think this will make it better to find people in the list and also better to use the keyboard to select counsellors.

2021-03-09 02:42 UTC, nickhurlburt commented
If you get an incoming contact and accept it, then you are unable to switch between that contact and the offline contact.  You have to finish the incoming contact before you can return to the offline contact.  

Ideally we could switch between them.  However, it may be fine to not support this now.  Please check with Dee in how important that is, if you haven't already.

2021-03-09 02:48 UTC, nickhurlburt commented
It doesn't look like this is displaying correctly in Search.  When I save a contact as being from another counsellor, in search it appears as me, both in the search results and the search detail.  Perhaps that's not part of this PR.

![image](https://user-images.githubusercontent.com/10714292/110411127-dd0ee280-803e-11eb-85e2-473c4767b474.png)

2021-03-09 02:51 UTC, nickhurlburt commented
Interesting... when I select this Location/Municipality combination, the District stays disabled:
![image](https://user-images.githubusercontent.com/10714292/110411322-35de7b00-803f-11eb-8886-76575cead858.png)

That is probably not related to this PR, but is this something we need to investigate, or is it already fixed elsewhere?

2021-03-09 02:53 UTC, nickhurlburt commented
When I create a case for an offline contact, that is also still recording me as the counsellor.  But again, perhaps this doesn't address that yet:

![image](https://user-images.githubusercontent.com/10714292/110411532-979ee500-803f-11eb-9841-96b6531825c3.png)

2021-03-09 02:54 UTC, nickhurlburt commented
The form layout looks correct:
![image](https://user-images.githubusercontent.com/10714292/110411599-b1d8c300-803f-11eb-8ba6-988f9a22df24.png)

Otherwise see several other comments above.

2021-03-12 15:57 UTC, GPaoloni commented
Closed in favor of https://github.com/tech-matters/flex-plugins/pull/374.

2021-03-12 15:57 UTC, closed without merging