Canned Responses feature for South Africa
tech-matters/flex-plugins pull request #404
Opened 2021-03-30 21:37 UTC by andvirga

WIP - DON'T MERGE YET

2021-03-31 21:33 UTC, nickhurlburt requested changes
Just a couple questions/comments inline.

There are a few larger points this PR touches on.  I'll mention them here, but they are not blocking for this:
1. We're putting a lot into our configuration `Definition Versions`.  One aspect of those is that they are versioned so that we can pull things out of the database properly.  So a question is then -- if we make a change to something like canned responses that doesn't affect saved database records, do we need an all-new definition version, such as `za-v2`?  I am not sure how to handle this... there is some overhead to creating a new Definition Version, but also overhead to separating it out.
2. As you mention in the investigation document, we want a way to have a counselor/supervisor edit these.
3. Creating separate flex plugins.  I don't think we need to do that now, but this may be a good thing to separate eventually.

2021-03-31 21:33 UTC, nickhurlburt commented on plugin-hrm-form/src/formDefinitions/za-v1/CannedResponses.json
> +    "text": "It’s understandable that you are worried about getting the COVID19 Virus, however, here are some tips to help you stay safe • Wash your hands regularly / use sanitizer • Avoid handshakes
Can we add newlines before the bullets so that it shows up in the chat as:
```
It’s understandable that you are worried about getting the COVID19 Virus, however, here are some tips to help you stay safe 
 • Wash your hands regularly / use sanitizer
 • Avoid handshakes, hugs and kisses.
 • Don’t touch your face unnecessarily 
[...]
```

2021-03-31 21:33 UTC, nickhurlburt commented on plugin-hrm-form/src/components/CannedResponses.tsx
> +        <Select value="" onChange={handleChange} name="canned_response">
I think we want to move more toward using standard HTML elements for the dropdown, as we are with selects within the customization framework.  Then it is more accessible and the keyboard can be used to go through the list -- for example, using the up/down arrow keys and typing the first letters of the option to pull it up.  But if there are problems with that option, we can discuss.

2021-03-31 21:33 UTC, nickhurlburt commented on plugin-hrm-form/src/components/CannedResponses.tsx
> +    Actions.invokeAction('SetInputText', {
Oh, of course... this is great.  So simple!

2021-04-01 14:11 UTC, andvirga commented on plugin-hrm-form/src/formDefinitions/za-v1/CannedResponses.json
> +    "text": "It’s understandable that you are worried about getting the COVID19 Virus, however, here are some tips to help you stay safe • Wash your hands regularly / use sanitizer • Avoid handshakes
Good catch! I've added new lines to other responses as well.

2021-04-01 19:00 UTC, andvirga commented on plugin-hrm-form/src/components/CannedResponses.tsx
> +        <Select value="" onChange={handleChange} name="canned_response">
Got it! I've replaced these material UI components with native HTML controls.

2021-04-01 19:10 UTC, andvirga commented
> Just a couple questions/comments inline.
> 
> There are a few larger points this PR touches on. I'll mention them here, but they are not blocking for this PR:
> 
> 1. We're putting a lot into our configuration `Definition Versions`.  One aspect of those is that they are versioned so that we can pull things out of the database properly.  So a question is then -- if we make a change to something like canned responses that doesn't affect saved database records, do we need an all-new definition version, such as `za-v2`?  I am not sure how to handle this... there is some overhead to creating a new Definition Version, but also overhead to separating it out.
> 2. As you mention in the investigation document, we want a way to have a counselor/supervisor edit these.
> 3. Creating separate flex plugins.  I don't think we need to do that now, but this may be a good thing to separate eventually.

About comment #1:
Good observation. I'm also not quite sure which is the best approach here. Strictly speaking, `CannedResponses` shouldn't be part of the Form Definitions (because it's not being used to build forms, only to populate a dropdown). However, there a lot of benefits to include that information there (easy to access from Flex-Plugins, easy to modify, etc.)
To answer your question I believe that when we modify something that is not related to the forms themselves (i.e: CannedResponses, OfficeInformation, etc.) **we don't need to create a new definition version**. However, we must create a new definition version if we have modified an entity that is used to build the forms (i.e: ChildInformation, CallerInfo, etc.)

2021-04-01 19:14 UTC, nickhurlburt approved these changes
Looks good!  As mentioned inline, it'd be good to wrap this in a feature flag

2021-04-01 19:14 UTC, nickhurlburt commented on plugin-hrm-form/src/HrmFormPlugin.js
> +  Components.setupCannedResponses();
Following our discussion today... can we wrap this in a feature flag?  This means we will be able to deploy the code before we want users to see it.  You can see an example of using feature flags at line 181 above.

2021-04-01 19:14 UTC, nickhurlburt commented on plugin-hrm-form/src/formDefinitions/za-v1/CannedResponses.json
> +[
I'd expect that Dee will want to make more edits to this, but we can get it on to Development as it is now.

2021-04-01 20:05 UTC, merged

2021-04-05 15:22 UTC, GPaoloni reviewed
Looks great! Random comments that maybe you already addressed in following PRs.

2021-04-05 15:22 UTC, GPaoloni commented on plugin-hrm-form/src/HrmFormPlugin.js
> +import CannedResponses from './components/CannedResponses';
Not used I believe?

2021-04-05 15:22 UTC, GPaoloni commented on plugin-hrm-form/src/components/CannedResponses.tsx
> +import {} from '@material-ui/core';
Delete this line?

2021-04-05 15:22 UTC, GPaoloni commented on plugin-hrm-form/src/components/CannedResponses.tsx
> +  FormOption,
Good reuse of this styles!

2021-04-05 15:22 UTC, GPaoloni commented on plugin-hrm-form/src/components/CannedResponses.tsx
> +export default connector(withTheme(CannedResponses));
What purpose is serving withTheme here?